# MeloDestra Configuration Example
# Copy this file to config.yml and adjust the settings as needed.

# NOTE: All settings in this file can be overridden by environment variables 
# (prefixed with MD_, e.g., MD_SPOTIPY_CLIENT_ID, MD_DISPLAY_GENRE).
# Environment variables take precedence over values in this file.
# See README.md for a full list of environment variables and their default values.

# --- API & Refresh ---
# Required Spotify Credentials (or set MD_SPOTIPY_CLIENT_ID and MD_SPOTIPY_CLIENT_SECRET env vars)
SPOTIPY_CLIENT_ID: 'YOUR_SPOTIFY_CLIENT_ID_HERE'
SPOTIPY_CLIENT_SECRET: 'YOUR_SPOTIFY_CLIENT_SECRET_HERE'

# Last.fm API Credentials (Optional but recommended - for genre/playcount)
# (or set MD_LASTFM_API_KEY, MD_LASTFM_SHARED_SECRET env vars)
# - If you want to use Last.fm for genre fetching and play counts, fill these in.
# - If left as placeholders or empty, Last.fm features will be disabled.
LASTFM_API_KEY: 'YOUR_LASTFM_API_KEY_HERE'
LASTFM_SHARED_SECRET: 'YOUR_LASTFM_SHARED_SECRET_HERE'

# Interval (in milliseconds) to poll Spotify for current song status
refresh_interval_ms: 5000

# --- Visuals & Colours ---
# ColourThief quality (1=highest, 10=default/faster). Lower values are slower but potentially more accurate.
# You can use 'colour_thief_quality' or 'color_thief_quality' in your config.yml
colour_thief_quality: 1 # or color_thief_quality: 1
# Luminance thresholds for forcing white text on mid-gray backgrounds
gray_zone_low: 0.30
gray_zone_high: 0.65

# --- Animated Background ---
# Settings for the dynamic gradient background animation
animated_background:
  enabled: true # Set to false to disable animation and use a static background
  palette_colours: 5 # Number of colours to extract for the gradient (3-8 recommended)
  duration: '45s' # Duration of one animation cycle (CSS time format)

# --- Animations ---
# Global animation ease function (CSS format)
animation_ease: 'cubic-bezier(0.25, 0.1, 0.25, 1.0)'
# Fade duration for track changes/show/hide (CSS format, e.g., '0.4s')
fade_duration: '0.4s'
# Stagger delay between elements during fades (milliseconds)
fade_stagger_ms: 50
# Ken Burns effect on artwork
ken_burns:
  enabled: true
  duration: '45s' # (CSS format)
  scale_factor: 1.05 # (e.g., 1.05 means zoom to 105%)

# --- Display Elements ---
# Show/hide specific UI elements
display:
  genre: true # Show genre information (requires Last.fm to be configured)
  like_icon: true
  shuffle_icon: true
  progress_bar: true
  time_info: true
  lastfm_playcount: true # Show Last.fm play count if Last.fm is configured & available
  hide_cursor: false # Hide cursor for kiosk mode (useful for Raspberry Pi displays)

# --- Last.fm Integration ---
# Requires LASTFM_API_KEY and LASTFM_SHARED_SECRET to be set above for genre/playcount features.
lastfm:
  username: ""    # Your Last.fm username (Required for listening history)

# --- Genre Display Settings (Blacklist because people tag some bullshit on last.fm) ---
genre_blacklist:
  - "lidarr"
  - "seen live"
  - "fip"
  - "favorite"
  - "favs"
  - "owned"
  - "wishlist"
  - "library"
  - "collection"
  - "to listen"
  - "buy"